name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

permissions:
  contents: 'read'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'Dockerfile'
              - 'dropbox'
              - 'entrypoint.sh'

      - name: Set up image tag
        run: |
          if "${{ github.ref }}" =~ refs/tags/v.+; then
            echo "IMAGE_TAG=${REF##*/v}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - run: echo "IMAGE_TAG=${IMAGE_TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: littlef/dropbox:${{ env.IMAGE_TAG }}

